### ISSUE TITLE
Compilation error: "call to function 'operator<<'..."

### ISSUE THREAD

**Issue by urban-1** [iszczesniak/gde#1]
Hello,

First of all, thanks for open sourcing your algorithm and for the really nice explanation in your paper :)

Compiling it today I got the following:

```
In file included from experimental/urban/gde/example.cc:2:
experimental/urban/gde/utils.hpp:15:36: error: call to function 'operator<<' that is neither visible in the template definition nor found by argument-dependent lookup
  os << "pair(" << p.first << ", " << p.second << ")";
                                   ^
experimental/urban/gde/example.cc:64:10: note: in instantiation of function template specialization 'operator<<<cunits<unsigned int>, std::__cxx11::list<boost::detail::edge_desc_impl<boost::directed_tag, unsigned long>, std::allocator<boost::detail::edge_desc_impl<boost::directed_tag, unsigned long> > > >' requested here
    cout << r.value();
         ^
experimental/urban/gde/utils.hpp:23:15: note: 'operator<<' should be declared prior to the call site or in an associated namespace of one of its arguments
std::ostream &operator << (std::ostream &os, const std::list<T> &v)
              ^
1 error generated.
```

C++ is not my strong suit (and STL exceptions are always giving me headaches), but from what I understand the issue is that the `&operator <<` on `pair` is somehow declared after it is being used.

It's my understanding that we are using it to print `std::pair<CU, path>` which is typedef-ed in graph.hpp, thus my current solution is to move the operator at the end of that header as:

```
std::ostream &operator << (std::ostream &os, const cupath &p)
{
  os << "pair(" << p.first << ", " << p.second << ")";
  return os;
}
```

This solves the issue for me but there might be a lot better solutions. Just thought of letting you know.

Thanks again

**Comment by iszczesniak** [comment]
Hi Andreas,

Thank you for dropping a note!  I'm glad to hear that you like the paper.

I can't replicate your problem.  Could you please tell me the compiler 
version you're using?  I'm using GCC 8.2.0 without problems.


Best,
Irek

**Comment by urban-1** [comment]
I am using `clang version 8.0.20181009`.

A similar case where gcc is working but clang is not can be found [here](https://stackoverflow.com/questions/31036530/cannot-compile-code-with-clang-but-works-with-gcc). This is the post that gave me the idea to move things around (started by declaring the operator straight into the main/example.cc).

**Comment by urban-1** [comment]
Hey, I just realised what's going on: 

- when printing << is called on the `std::pair<CU, path>`
- path is of `list<T>`
- << is now called on the `list<T>`
- list's operator is declared _after_ the pair one resulting in the above error (notice the character pointer is in `p.second` and actually the 3rd message states that)

Fixing is as simple as moving the pair operator after the list one in the same file. This keeps the API clean and as intended.

Hope it helps

PS: Still warming up on C++... too much Python lately :)

**Comment by iszczesniak** [comment]
Andreas, thanks for your email.  I'm sorry I'm responding late, but I'm 
finishing a paper for a conference.  I'll respond with some technical 
detail in a few days.

**Comment by iszczesniak** [comment]
Thanks, Andreas, for the fix!  Now the code builds with GCC and clang:

https://travis-ci.org/iszczesniak/gde
